version: '3'
    
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=exia
            - POSTGRES_USER=stratos
            - POSTGRES_PASSWORD=kyrios
            - PGDATA=/var/lib/postgresql/data/ 
        ports:
            - "5432:5432"
        volumes:
            - db-data/var/lib/postgresql/data/ 
    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: connor.richmondclark@thekeysupport.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8080:80"
        volumes:
            - pg-data/var/lib/pgadmin
        links:
            - "db:pgsql-server"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    db-data:
    pg-data: