version: '3'
    
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=exia
            - POSTGRES_USER=stratos
            - POSTGRES_PASSWORD=kyrios
        ports:
            - "5432:5432"
        volumes:
            - db-data:/db-data/var/lib/postgresql/data/
    djangoapp:
        build:
            context: .
            dockerfile: ./DockerfileDev
        image: djangoapp:dev
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/web
        ports:
            - "8000:8000"
        depends_on:
            - db
volumes:
    db-data:
    pga-data:
    pg-data:


        # pgadmin:
        #     image: dpage/pgadmin4
        #     restart: always
        #     environment:
        #         PGADMIN_DEFAULT_EMAIL: connor.richmondclark@thekeysupport.com
        #         PGADMIN_DEFAULT_PASSWORD: password
        #         PGADMIN_LISTEN_PORT: 80
        #     ports:
        #         - "8080:80"
        #     volumes:
        #         - pga-data:/pg-data/var/lib/pgadmin
        #     links:
        #         - "db:pgsql-server"