version: '3'

volumes:
    db-data:
    static: 
    app:
services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=exia
            - POSTGRES_USER=stratos
            - POSTGRES_PASSWORD=kyrios
        ports:
            - "5432:5432"
        volumes:
            - db-data/db-data/var/lib/postgresql/data/ 
    app:
        build: 
            context: .
            dockerfile: ./DockerfileProd
        image: djangoapp:prod
        command: gunicorn -w 4 btre.wsgi -b 0.0.0.0:8000
        volumes:
            - static:/code/static
        ports:
            - "8000:8000"
        depends_on:
            - db
            - nginx
    nginx:
        build:
            context: .
            dockerfile: ./DockerfileNGINX
        ports:
            - 80:80
        volumes:
            - static:/code/static


        # pgadmin:
        #     image: dpage/pgadmin4
        #     restart: always
        #     environment:
        #         PGADMIN_DEFAULT_EMAIL: connor.richmondclark@thekeysupport.com
        #         PGADMIN_DEFAULT_PASSWORD: password
        #         PGADMIN_LISTEN_PORT: 80
        #     ports:
        #         - "8080:80"
        #     volumes:
        #         - ./pg-data/var/lib/pgadmin
        #     links:
        #         - "db:pgsql-server"