# Generated by Django 2.2.12 on 2020-04-30 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('seller_of_month', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(
                    verbose_name=datetime.datetime.now)),
            ],
        ),
    ]
